apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot-p
spec:
  disruption:
    consolidateAfter: 10m # Terminate nodes 10 minutes after they become empty
    consolidationPolicy: WhenEmptyOrUnderutilized # Consolidate underutilized nodes

  template:
    metadata:
      labels:
        workload: fine-tuning
        gpu: nvidia-h100
        capacity-type: spot
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default #use default NodeClass
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["p5.48xlarge"]
      taints:
        - key: nvidia.com/gpu
          effect: NoSchedule

  limits:
    nodes: 2 # Maximum of 2 nodes can be provisioned dynamically
