apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-spot-dynamic
spec:
  # replicas: 2 # Maintain exactly 2 node (static capacity)

  disruption:
    consolidateAfter: 10m # Terminate nodes 1 minute after they become empty
    consolidationPolicy: WhenEmptyOrUnderutilized # Consolidate underutilized nodes

  template:
    metadata:
      labels:
        workload: fine-tuning
        gpu: nvidia-h100
        capacity-type: spot
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default #use default NodeClass
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["p5.48xlarge"]
        - key: vpc.amazonaws.com/efa
          operator: Exists
      taints:
        - key: nvidia.com/gpu
          effect: NoSchedule
      startupTaints:
        - key: node.kubernetes.io/not-ready
          effect: NoSchedule
      terminationGracePeriod: 24h0m0s

  limits:
    nodes: 2 # Maximum of 10 nodes can be provisioned dynamically
